### ISSUE TITLE
Data ingestion notebook processing job error

### ISSUE THREAD

**Issue by austinmw** [aws-samples/llm-apps-workshop#3]
I received the following error while running the step `Create and run the Sagemaker Processing Job` in the notebook `data_ingestion_to_vectordb.ipynb`:

```python
2023-05-23 15:35:48,581,2568289917,MainProcess,INFO,base_job_name=llm-apps-blog-job, tags=[{'Key': 'data', 'Value': 'embeddings-for-llm-apps'}], image_uri=197237853439.dkr.ecr.us-east-1.amazonaws.com/load-data-opensearch-custom:latest, instance_type=ml.m5.xlarge, instance_count=3
2023-05-23 15:35:48,615,2568289917,MainProcess,INFO,creating an opensearch index with name=llm_apps_workshop_embeddings
2023-05-23 15:35:49,020,session,MainProcess,INFO,Creating processing-job with name llm-apps-blog-job-2023-05-23-15-35-48-616
........................
Traceback (most recent call last):
  File "/opt/ml/processing/input/code/load_data_into_opensearch.py", line 24, in <module>
    from langchain.document_loaders import ReadTheDocsLoader
  File "/usr/local/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/usr/local/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/usr/local/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/usr/local/lib/python3.9/site-packages/langchain/memory/__init__.py", line 23, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/usr/local/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "/opt/ml/processing/input/code/load_data_into_opensearch.py", line 24, in <module>
    from langchain.document_loaders import ReadTheDocsLoader
  File "/usr/local/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/usr/local/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/usr/local/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/usr/local/lib/python3.9/site-packages/langchain/memory/__init__.py", line 23, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/usr/local/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "/opt/ml/processing/input/code/load_data_into_opensearch.py", line 24, in <module>
    from langchain.document_loaders import ReadTheDocsLoader
  File "/usr/local/lib/python3.9/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/usr/local/lib/python3.9/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/usr/local/lib/python3.9/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/usr/local/lib/python3.9/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/usr/local/lib/python3.9/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/usr/local/lib/python3.9/site-packages/langchain/memory/__init__.py", line 23, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/usr/local/lib/python3.9/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
Cell In[27], line 34
     32 # ready to run the processing job
     33 st = time.time()
---> 34 processor.run(code="container/load_data_into_opensearch.py",
     35               inputs=inputs,
     36               outputs=[],
     37               arguments=["--opensearch-cluster-domain", opensearch_domain_endpoint,
     38                          "--opensearch-secretid", os_creds_secretid_in_secrets_manager,
     39                          "--opensearch-index-name", opensearch_index,
     40                          "--aws-region", aws_region,
     41                          "--embeddings-model-endpoint-name", embeddings_model_endpoint_name,
     42                          "--chunk-size-for-doc-split", str(CHUNK_SIZE_FOR_DOC_SPLIT),
     43                          "--chunk-overlap-for-doc-split", str(CHUNK_OVERLAP_FOR_DOC_SPLIT),
     44                          "--input-data-dir", "/opt/ml/processing/input_data",
     45                          "--create-index-hint-file", CREATE_OS_INDEX_HINT_FILE,
     46                          "--process-count", "2"])
     47 time_taken = time.time() - st
     48 logger.info(f"processing job completed, total time taken={time_taken}s")

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/workflow/pipeline_context.py:300, in runnable_by_pipeline.<locals>.wrapper(*args, **kwargs)
    296         return context
    298     return _StepArguments(retrieve_caller_name(self_instance), run_func, *args, **kwargs)
--> 300 return run_func(*args, **kwargs)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/processing.py:684, in ScriptProcessor.run(self, code, inputs, outputs, arguments, wait, logs, job_name, experiment_config, kms_key)
    682 self.jobs.append(self.latest_job)
    683 if wait:
--> 684     self.latest_job.wait(logs=logs)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/processing.py:1109, in ProcessingJob.wait(self, logs)
   1102 """Waits for the processing job to complete.
   1103 
   1104 Args:
   1105     logs (bool): Whether to show the logs produced by the job (default: True).
   1106 
   1107 """
   1108 if logs:
-> 1109     self.sagemaker_session.logs_for_processing_job(self.job_name, wait=True)
   1110 else:
   1111     self.sagemaker_session.wait_for_processing_job(self.job_name)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:4741, in Session.logs_for_processing_job(self, job_name, wait, poll)
   4738             state = LogState.JOB_COMPLETE
   4740 if wait:
-> 4741     _check_job_status(job_name, description, "ProcessingJobStatus")
   4742     if dot:
   4743         print()

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/session.py:6580, in _check_job_status(job, desc, status_key_name)
   6574 if "CapacityError" in str(reason):
   6575     raise exceptions.CapacityError(
   6576         message=message,
   6577         allowed_statuses=["Completed", "Stopped"],
   6578         actual_status=status,
   6579     )
-> 6580 raise exceptions.UnexpectedStatusException(
   6581     message=message,
   6582     allowed_statuses=["Completed", "Stopped"],
   6583     actual_status=status,
   6584 )

UnexpectedStatusException: Error for Processing job llm-apps-blog-job-2023-05-23-15-35-48-616: Failed. Reason: AlgorithmError: See job logs for more information
```

**Comment by aarora79** [comment]
I was able to run this without any error, no special steps, just ran the cloud formation template in `us-east-1` and then did a run all on the `data_ingestion_to_vectordb.ipynb` notebook. Could you confirm if you made any changes to the notebook? Which region did you run this in?

**Comment by austinmw** [comment]
Hi @aarora79 , I ran the notebook in us-east-1. The steps I followed were simply:
1. Click the us-east-1 deploy button, click through to deploy the stack
2. Find the notebook url, navigate to the ipynb, select "Run All"

I tried this a second time and received the same error.

**Comment by austinmw** [comment]
We got this fixed, needed to update pydantic.
